# Site/SEO settings
email: jonatasemidio@gmail.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Jonatas Emidio 
title: OverHackingView
description: >
  This is a place to share more then just hello world!.
url: http://overhackingview.com
twitter_username: jonatasemidio
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/jonatasemidio
  - name: instagram
    url: https://www.instagram.com/jonatases/
  - name: linkedin
    url: https://www.linkedin.com/in/jonatasemidio/
  - name: github
    url: https://github.com/jonatasemidio

# Contact settings
contact_img: /assets/images/post.jpg
formcarry: https://formcarry.com/s/mUixFySPBwB

# Disqus settings
disqus: overhackingview

# MailChimp settings
mailchimp_action: https://frevoo.us6.list-manage.com/subscribe/post?u=0c80b66360862ed72c16dcb96&amp;id=5d3de04c7d
mailchimp_input: b_0c80b66360862ed72c16dcb96_5d3de04c7d

# Author settings
author:
  - name: Jonatas Emidio
    bio: I Love My Familly, Friends, Rock, Code, Skate, Cinema and The creator of everything (I use to call him God!).
    url: #

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
